// flow-typed signature: 6ee03f96778e01b7308658fbb834dbcf
// flow-typed version: <<STUB>>/@grpc/proto-loader_v^0.5.1/flow_v0.101.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@grpc/proto-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@grpc/proto-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@grpc/proto-loader/build/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@grpc/proto-loader/build/src/index.js' {
  declare module.exports: $Exports<'@grpc/proto-loader/build/src/index'>;
}
